INSERT INTO app_user (id, username, first_name, last_name, email, password, gender, day_of_birth, image_url)
VALUES (DEFAULT, 'CrazyJohnny', 'John', 'Doe', 'JohnDoe12@gmail.com', 'HardPASSword123', 'Male', '2001-01-01', 'temp'),
       (DEFAULT, 'JustJane777', 'Jane', 'Smith', 'janejanejane@yahoo.com', '777enajtsuj', 'Female', '1992-10-02', 'temp'),
       (DEFAULT, 'placeholder3', 'Michael', 'Johnson', 'placeholder3@gmail.com', 'Michael9090', 'Male', '2005-03-10', 'temp'),
       (DEFAULT, 'ksjcnjfiuowurjh', 'Emily', 'Williams', 'Emilly.Williams@icloud.com', 'sfwegset342@dew', 'Female', '1994-04-01',
        'temp'),
       (DEFAULT, 'TooHotToHandle', 'Daniel', 'Brown', 'WhooperMAXXX@yahoo.com', 'Daniel0505', 'Male', '1995-05-05', 'temp'),
       (DEFAULT, 'SpeedyGonzales', 'Gonzales', 'Rodriguez', 'speedy@gmail.com', 'speedy123', 'Male', '1996-01-06', 'temp'),
       (DEFAULT, 'MissyMiss', 'Melissa', 'Garcia', 'missymiss@hotmail.com', 'hello123', 'Female', '1997-07-08', 'temp'),
       (DEFAULT, 'RockingRobin', 'Robert', 'Robinson', 'rockinrobin@yahoo.com', 'robinrocks', 'Male', '1998-08-04', 'temp'),
       (DEFAULT, 'DancingQueen', 'Olivia', 'Martinez', 'dancequeen@gmail.com', 'dancing321', 'Female', '1999-09-01', 'temp'),
       (DEFAULT, 'StarryNight', 'Vincent', 'Van Gogh', 'starrynight@yahoo.com', 'vangogh1888', 'Male', '2000-04-10', 'temp'),
       (DEFAULT, 'FancyPants', 'Frank', 'White', 'fancypants@icloud.com', 'password123', 'Male', '1988-08-04', 'temp'),
       (DEFAULT, 'ShiningStar', 'Samantha', 'Johnson', 'shiningstar@icloud.com', 'starshine123', 'Female', '1986-04-06', 'temp'),
       (DEFAULT, 'MightyMouse', 'Mark', 'Taylor', 'mightymouse@yahoo.com', 'mousepower123', 'Male', '1984-04-04', 'temp'),
       (DEFAULT, 'SparklingSoul', 'Sara', 'Anderson', 'sparklingsoul@yahoo.com', 'soulsparkle123', 'Female', '1982-10-02',
        'temp'),
       (DEFAULT, 'GoldenHeart', 'Gary', 'Brown', 'goldenheart@gmail.com', 'heartofgold123', 'Male', '1989-10-08', 'temp'),
       (DEFAULT, 'SilverLining', 'Samantha', 'White', 'silverlining@icloud.com', 'silver123', 'Female', '1978-10-08', 'temp'),
       (DEFAULT, 'RockStar', 'Robert', 'Johnson', 'rockstar@outlook.com', 'rockon123', 'Male', '1996-08-10', 'temp'),
       (DEFAULT, 'DivaQueen', 'Danielle', 'Davis', 'divaqueen@outlook.com', 'divadiva444', 'Female', '1974-04-10', 'temp'),
       (DEFAULT, 'TechieGuy', 'Thomas', 'Taylor', 'techieguy@outlook.com', 'tech87281', 'Male', '2009-10-02', 'temp'),
       (DEFAULT, 'Fashionista', 'Fiona', 'Fisher', 'fashionista@outlook.com', 'fashion000', 'Female', '1971-04-08', 'temp');
