INSERT INTO app_user (username, first_name, last_name, email, password, gender, day_of_birth, image)
VALUES ('CrazyJohnny', 'John', 'Doe', 'JohnDoe12@gmail.com', 'HardPASSword123', 'Male', '2001-01-01', null),
       ('JustJane777', 'Jane', 'Smith', 'janejanejane@yahoo.com', '777enajtsuj', 'Female', '1992-10-02', null),
       ('placeholder3', 'Michael', 'Johnson', 'placeholder3@gmail.com', 'Michael9090', 'Male', '2005-03-10', null),
       ('ksjcnjfiuowurjh', 'Emily', 'Williams', 'Emilly.Williams@icloud.com', 'sfwegset342@dew', 'Female', '1994-04-01', null),
       ('TooHotToHandle', 'Daniel', 'Brown', 'WhooperMAXXX@yahoo.com', 'Daniel0505', 'Male', '1995-05-05', null),
       ('SpeedyGonzales', 'Gonzales', 'Rodriguez', 'speedy@gmail.com', 'speedy123', 'Male', '1996-01-06', null),
       ('MissyMiss', 'Melissa', 'Garcia', 'missymiss@hotmail.com', 'hello123', 'Female', '1997-07-08', null),
       ('RockingRobin', 'Robert', 'Robinson', 'rockinrobin@yahoo.com', 'robinrocks', 'Male', '1998-08-04', null),
       ('DancingQueen', 'Olivia', 'Martinez', 'dancequeen@gmail.com', 'dancing321', 'Female', '1999-09-01', null),
       ('StarryNight', 'Vincent', 'Van Gogh', 'starrynight@yahoo.com', 'vangogh1888', 'Male', '2000-04-10', null),
       ('FancyPants', 'Frank', 'White', 'fancypants@icloud.com', 'password123', 'Male', '1988-08-04', null),
       ('ShiningStar', 'Samantha', 'Johnson', 'shiningstar@icloud.com', 'starshine123', 'Female', '1986-04-06', null),
       ('MightyMouse', 'Mark', 'Taylor', 'mightymouse@yahoo.com', 'mousepower123', 'Male', '1984-04-04', null),
       ('SparklingSoul', 'Sara', 'Anderson', 'sparklingsoul@yahoo.com', 'soulsparkle123', 'Female', '1982-10-02', null),
       ('GoldenHeart', 'Gary', 'Brown', 'goldenheart@gmail.com', 'heartofgold123', 'Male', '1989-10-08', null),
       ('SilverLining', 'Samantha', 'White', 'silverlining@icloud.com', 'silver123', 'Female', '1978-10-08', null),
       ('RockStar', 'Robert', 'Johnson', 'rockstar@outlook.com', 'rockon123', 'Male', '1996-08-10', null),
       ('DivaQueen', 'Danielle', 'Davis', 'divaqueen@outlook.com', 'divadiva444', 'Female', '1974-04-10', null),
       ('TechieGuy', 'Thomas', 'Taylor', 'techieguy@outlook.com', 'tech87281', 'Male', '2009-10-02', null),
       ('Fashionista', 'Fiona', 'Fisher', 'fashionista@outlook.com', 'fashion000', 'Female', '1971-04-08', null);